CREATE TABLE "GCG_5667_BOMEXPLODE" (
 "ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_ID" UNIQUE USING 0,
 "RUN_ID" INTEGER,
 "PARENT" CHAR(20),
 "SEQUENCE" CHAR(10),
 "PART" CHAR(20),
 "DESCRIPTION" CHAR(30) );